//Combierte los n aravicos a n romanos.
#include<stdio.h>
#include<conio.h>
#include<string.h> \\No es necerario poner esta libreria.
void main()
{
clrscr();
int nu=1;
while(nu<90)
{
printf("\t\t \t\tPROGRAMA <<<< SET 1.0.8 >>>>\n");
printf("\t\t \t <<<<< CONVERTIR DE --NU--ARAVIGOS A --NU-- ROMANOS>>>>\n");
printf("\t\t********* PARA SALIR INGRESE EL NUMERO  [ 101 ] ***********\n");
printf("Ingrse el numero   ");
scanf("\n%i",& nu);
switch(nu)
{
case 1:
printf("I");
break;
case 2:
printf("II");
break;
case 3:
printf("III");
break;
case 4:
printf("IV");
break;
case 5:
printf("V");
break;
case 6:
printf("VI");
break;
case 7:
printf("VII");
break;
case 8:
printf("VIII");
break;
case 9:
printf("IX");
break;
case 10:
printf("X");
break;
case 11:
printf("XI");
break;
case 12:
printf("XII");
break;
case 13:
printf("XIII");
break;
case 14:
printf("XIV");
break;
case 15:
printf("XV");
break;
case 16:
printf("XVI");
break;
case 17:
printf("XVII");
break;
case 18:
printf("XVIII");
break;
case 19:
printf("XIX");
break;
case 20:
printf("XX");
break;
case 21:
printf("XXI");
break;
case 22:
printf("XXII");
break;
case 23:
printf("XXIII");
break;
case 24:
printf("XXIV");
break;
case 25:
printf("XXV");
break;
case 26:
printf("XXVI");
break;
case 27:
printf("XXVII");
break;
case 28:
printf("XXVIII");
break;
case 29:
printf("XXIX");
break;
case 30:
printf("XXX");
break;
case 31:
printf("XXXI");
break;
case 32:
printf("XXXII");
break;
case 33:
printf("XXXIII");
break;
case 34:
printf("XXXIV");
break;
case 35:
printf("XXXV");
break;
case 36:
printf("XXXVI");
break;
case 37:
printf("XXXVII");
break;
case 38:
printf("XXXVIII");
break;
case 39:
printf("XXXIX");
break;
case 40:
printf("XL");
break;
case 41:
printf("XLI");
break;
case 42:
printf("XLII");
break;
case 43:
printf("XLIII");
break;
case 44:
printf("XLIV");
break;
case 45:
printf("XLV");
break;
case 46:
printf("XLVI");
break;
case 47:
printf("XLVII");
break;
case 48:
printf("XLVIII");
break;
case 49:
printf("XLIX");
break;
case 50:
printf("L");
break;
case 51:
printf("LI");
break;
case 52:
printf("LII");
break;
case 53:
printf("LIII");
break;
case 54:
printf("LIV");
break;
case 55:
printf("LV");
break;
case 56:
printf("LVI");
break;
case 57:
printf("LVII");
break;
case 58:
printf("LVIII");
break;
case 59:
printf("LIX");
break;
case 60:
printf("LX");
break;
case 61:
printf("LXI");
break;
case 62:
printf("LXII");
break;
case 63:
printf("LXIII");
break;
case 64:
printf("LXIV");
break;
case 65:
printf("LXV");
break;
case 66:
printf("LXVI");
break;
case 67:
printf("LXVII");
break;
case 68:
printf("LXVIII");
break;
case 69:
printf("LXIX");
break;
case 70:
printf("LXX");
break;
case 71:
printf("LXXI");
break;
case 72:
printf("LXXII");
break;
case 73:
printf("LXXIII");
break;
case 74:
printf("LXXIV");
break;
case 75:
printf("LXXV");
break;
case 76:
printf("LXXVI");
break;
case 77:
printf("LXXVII");
break;
case 78:
printf("LXXVIII");
break;
case 79:
printf("LXXIX");
break;
case 80:
printf("LXXX");
break;
case 81:
printf("LXXXI");
break;
case 82:
printf("LXXXII");
break;
case 83:
printf("LXXXIII");
break;
case 84:
printf("LXXXIV");
break;
case 85:
printf("LXXXV");
break;
case 86:
printf("LXXXVI");
break;
case 87:
printf("LXXXVII");
break;
case 88:
printf("LXXXVIII");
break;
case 89:
printf("LXXXIX");
break;
case 90:
printf("XC");
bresk;
case 91:
printf("XCI");
break;
case 92:
printf("XCII");
break;
case 93:
printf("XCIII");
break;
case 94:
printf("XCIV");
break;
case 95:
printff("XCV");
break;
case 96:
printf("XCVI");
break;
case 97:
printf("XCVII");
break;
case 98:
printf("XCVIII");
break;
case 99:
printf("XCIX");
break;
case 100:
printf("C");
break;
case 101:
printf("SALIR");
break;
}
getch();
clrscr();
}
}
